[build]
  command = "npm run final:ssr"
  publish = "dist/HomeSync/browser"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "api"
  included_files = ["dist/**", "node_modules/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200