[build]
  command = "npm run build:ssr"
  publish = "dist/HomeSync/browser"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  conditions = {Role = ["admin", "user"]}

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[functions]]
  name = "server"
  runtime = "nodejs20.x"